### ISSUE TITLE
Providing metadata via the extension

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/carpentries-quarto#1]
The carpentries html templates use mustache to get certain variables.
Most can be directly translated to quarto yml metadata if we add in a few things that pkgdown added during the build process (at the bottom is an example yml file for a pre-alpha incubator lesson).

There is still the problem of the translatable elements. I think this can be done by suppyling metadata files via the extension:

```yaml
contributes:
  metadata:
    metadata-files:
      - translate_en.yml
```
in `translate_en.yml`:
```yaml
translate:
  SkipToMain: "Skip to Main"
  PreAlphaNote: "Pre-alpha"
```

```yaml
# ------------------------------------------------------------------ information
# This file was generated by sandpaper version '0.16.2'
# If you want to make changes, please edit 'E:/Documents/astroDimitrios/intro-to-modern-fortran/config.yaml'
# ------------------------------------------------------------------ information

title: Introduction to Modern Fortran
lang: en
home:
  title: Home
  strip_header: yes
  description: ~
template:
  package: varnish
  params:
    time: 2024-06-25 22:30:50 +0000
    source: https://github.com/astroDimitrios/intro-to-modern-fortran
    branch: main
    contact: d.theodorakis@metoffice.gov.uk
    license: CC-BY 4.0
    handout: ~
    cp: no
    lc: no
    dc: no
    swc: no
    carpentry: incubator
    carpentry_name: Carpentries Incubator
    carpentry_icon: incubator
    life_cycle: pre-alpha
    pre_alpha: yes
    alpha: no
    beta: no
    stable: no
    doi: ~
    title: Introduction to Modern Fortran
    created: '2023-08-04'
    keywords: software, data, lesson, The Carpentries, Fortran
    episodes: introduction.Rmd
    learners: ~
    instructors: ~
    profiles: ~
```
